FROM postgres:15

RUN apt update && apt install -y postgresql-15-wal2json postgresql-15-decoderbufs
COPY ["./config-files/postgresql-15.conf", "/etc/postgresql/postgresql.conf"]
COPY ["./docker-entrypoint-initdb.d/*", "/docker-entrypoint-initdb.d/"]

